version: '3.7'
services:
  quasar:
    build:
      context: './app/'
      target: 'develop-stage'
    container_name: 'app'
    ports:
    - '8080:8080'
    volumes:
    - './app/:/app'
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: /bin/sh -c "yarn && quasar dev"
